### ISSUE TITLE
Confusion With Holes

### ISSUE THREAD

**Issue by infosisio** [JohK/nutsnbolts#15]
The holes seem to be like a cylinder with fn set to 8.

Is this going to work as a threaded hole when you print the item?

**Comment by JohK** [comment]
To generate a threaded hole, the parameter "thread" has to be set to
"modeled".

In CAD it is very untypical to model threads, which is why in this library
the default is not to model threads. This is a library that intents to
support good engineering practice for CAD modelling.

Holes clearances default to values that for smallers bolt sizes should
allow to screw the bolt into the plastic (without any actual thread being
printed).
